#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
    if [ $(crontab -l | grep -c "poddns") = 0 ]; then
        (crontab -l 2>/dev/null; echo "* */2 * * * /usr/share/autoban/autoban.sh") | crontab -
    fi
}

stop() {
    (crontab -l 2>/dev/null | sed '/autoban/d') | crontab -
}

restart() {
    start
    stop
    /usr/share/autoban/autoban.sh
}